stage('Install dependencies') {
    steps {
        sh 'python3 -m pip install --no-cache-dir -r requirements.txt'
    }
}

stage('Run Buyback Detector') {
    steps {
        sh '''
            if [ ! -f "$WORKSPACE/notified.json" ]; then
                echo '{}' > $WORKSPACE/notified.json
            fi
            python3 scripts/check_buybacks_finnhub.py
        '''
    }
}
